# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 617097f712443cdd9315ab40d365d8419610a79caddbc8ca10a40a0c7702204d3be5bdb09cd44a2c76c199240b0f90e1bdc574b2a9a1311cb4e710b22824109b

test:
  secret_key_base: 6b6b8901f25356577683353f58622db348091b762d737db9279a719ad9f1832cb6e41598e8f1b3bee3f399e4405a05d483859746e6b2e058a86f6c02517d2890

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
